<html>
<head>
<title>Login</title>
</head>
<body>
<h1>Please Login</h1>

<table><form method="post" action=""/>
<tr>
<td>
<label for="username">Username</label>
</td>
<td>
<input type="text" id="username" name="username" />
</td>
</tr>
<tr>
<td>
<label for="password">Password</label>
</td>
<td>
<input type="password" id="password" name="password"  />
</td>
</tr>
<tr>
<td colspan="2"><input type="submit" value="Login" /></td>
</tr></form>
</table>
</body>
</html>
